import { array, bool, date, func, number, object, string } from 'prop-types';

export default {
  BUTTON: {
    delay: number,
    icon: string,
    onPress: func,
  },
  CURRENCIES: {
    BTC: number,
    LTC: number,
  },
  DEVICE: {
    id: string,
    currency: string,
    devices: array,
    image: string,
    name: string,
    push: string,
    private: object, // { capture: string, passport: string, phone: string },
    requests: array,
    state: string,
    token: string,
    createdAt: date,
  },
  NAVIGATION: {
    navigate: func,
    setParams: func,
  },
  TRANSACTION: {
    id: string,
    amount: number,
    charge: number,
    coin: string,
    concept: string,
    confirmations: number,
    createdAt: date,
    fee: number,
    payment: bool,
    state: string,
    from: object,
    to: object,
  },
  WALLET: {
    id: string,
    address: string,
    balance: number,
    coin: string,
    imported: bool,
    name: string,
    lastBlockheight: string,
    progress: number,
    readOnly: bool,
    trend: number,
    type: string,
    wif: string,
    hexSeed: string,
  },
};
