import { array, bool, date, func, number, object, string } from 'prop-types';

export default {
  BUTTON: {
    delay: number,
    icon: string,
    onPress: func,
  },
  CURRENCIES: {
    BTC: number,
    LTC: number,
    ETH: number,
  },
  DEVICE: {
    id: string,
    currency: string,
    devices: array,
    image: string,
    language: string,
    name: string,
    push: string,
    pin: string,
    requests: array,
    state: string,
    token: string,
    trend: string,
    createdAt: date,
  },
  ERROR: {
    code: number,
    title: string,
    message: string,
  },
  FEES: {
    fast: number,
    regular: number,
    slow: number,
    charge: number,
  },
  I18N: {},
  NAVIGATION: {
    navigate: func,
    setParams: func,
  },
  RECIPIENT: {
    device: object,
    wallet: object,
    address: string,
  },
  TRANSACTION: {
    id: string,
    amount: number,
    blockHeight: number,
    charge: number,
    coin: string,
    concept: string,
    confirmations: number,
    createdAt: date,
    fee: number,
    payment: bool,
    product: string,
    state: string,
    from: object,
    to: object,
  },
  WALLET: {
    id: string,
    address: string,
    balance: number,
    coin: string,
    deviceId: string,
    imported: bool,
    name: string,
    lastBlockheight: string,
    progress: number,
    readOnly: bool,
    trend: number,
    type: string,
  },
};
