export default {
  EN: {
    ACCEPT: 'Accept',
    ADD_NOTE: 'Add note',
    ADDRESS: 'Address',
    ARCHIVE_WALLET: 'Archive this wallet',

    BALANCE: 'Balance',

    CANCEL_REQUEST: 'Cancel request',
    CHANGE_YOUR_AVATAR: 'Change your avatar',
    CHOOSE_A_FRIEND: 'Choose a friend',
    CHOOSE_CURRENCY: 'Choose your local currency',
    CHOOSE_EXISTING_PHOTO: 'Choose existing photo',
    CHOOSE_LANGUAGE: 'Choose your language',
    CONCEPT: 'Concept',
    CONFIRMATIONS: 'Confirmations',
    COPYRIGHT: 'Made by a small band of superheroes in London. Thank you for your support!',
    CREATE: 'create',
    CREATE_BACKUP: 'Create a backup',
    CREATE_FIRST_WALLET: 'Create your first wallet',

    DATE: 'Date',
    DEPOSIT: 'Deposit',

    ERROR_CONNECTION: 'Oops, seems you are not connected to splitbits server.',

    FEE: 'Fee',
    FRIENDS: 'Friends',
    FROM: 'From',

    HASH: 'Hash',
    HINT_FIND_BY_NAME: 'Other people can only find you if you have defined your name.',

    IMPORT: 'import',
    IMPORT_ADDRESS: 'If you import a public address your wallet will be in watch only mode.',

    LANGUAGE: 'Language',
    LOCAL_CURRENCY: 'Local currency',

    NAME: 'Name',
    NEW_WALLET: 'New Wallet',
    NEXT: 'Next',

    PAPER_KEY: 'Paper key',
    PAPER_KEY_DONE: 'Already written my paper key',
    PAPER_WALLET: 'Your paper key is the only way to restore your wallet if your phone is lost, stolen, broken, or upgraded. This is your list of words to write down on a piece of paper and keep safe.',
    PAY: 'Pay',
    PAYMENT: 'Payment',
    PAYMENT_REQUEST: 'Payment requests',
    PORTFOLIO: 'Stay on top of your portfolio. Anytime. Anywhere.',
    PROCESSING: 'Processing...',
    PROFILE_QR: 'This QR will help your friends to find you easily.',

    READ_ONLY: 'Watch only',
    RECOVER_PAPER_WALLET: 'Recovering another wallet allows you to access and manage a different wallet on this device. Enter the Paper Key.',
    RECOVER: 'recover',
    REQUEST: 'Request',
    REQUEST_MONEY: 'Request funds',
    REQUEST_MONEY_HINT: 'You can ask money in your private network.',
    REQUEST_MONEY_HINT_NO_FRIENDS: 'Add friends in order to request money.',

    SEARCH: 'Search...',
    SEND: 'Send',
    SEND_MONEY: 'Send Money',
    SEND_MONEY_HINT: 'Send money to any wallet in the world.',
    SEND_MONEY_HINT_NO_BALANCE: 'Top-up your wallet to send money.',
    SEND_MONEY_HINT_READ_ONLY: "You can't send money from a watch only wallet.",
    SETTINGS: 'Settings',
    SET_PIN_CODE: 'Set your PIN code',
    SKIP: 'Skip',
    START: 'Start',
    STATE: 'State',
    SWITCH_PRO: 'Switch to PRO',

    TAKE_PHOTO: 'Take photo',
    TO: 'To',
    TRANSACTION: 'Transaction',
    TYPE_OF_TRANSACTION: 'Type of transaction',
    TYPE_OF_WALLET: 'Type of wallet',

    USE_PUBLIC_ADDRESS: 'or use a public address',
    USE_FINGERPRINT: 'Use fingerprint to unlock',

    WAIT_A_MOMENT: 'Wait a moment',
    WALLET: 'Wallet',
    WORD: 'Word',

    CAPTION: {
      ARCHIVE_WALLET: 'If you do not want to use this wallet anymore.',
      CAMERA_PERMISSION: 'Give the app camera permissions in order to read QR codes',
      CREATE_BACKUP: 'The simplest way to have control of your wallet.',
      EXCHANGE: 'Use your local currency',
      NETWORK: 'Your private network',
      PRIVACY: 'Your privacy matters',
      PRIVATE_KEYS: 'Owner of your keys',
      QR_CODE: 'Place the code inside the frame',
      SWITCH_PRO: 'Super powers for your wallet.',
      WALLET: "Congrats, you're ready!",
      WELCOME: 'Welcome to splitbits',
    },
    HINT: {
      EXCHANGE: 'This world is still paid with local currencies. Do not worry we make your life easier when it comes to paying with your crypto coins.',
      NETWORK: 'Forget public addresses or QR codes. You can create your own private network of friends to speed up your payments.',
      PRIVACY: 'You do not need to give us your personal information. We do not want to know your email or social networks. We just want you to enjoy this wallet.',
      PRIVATE_KEYS: 'Your private keys always go with you, we never save them in our cloud. We offer you tools so that you can recover them easily.',
      WALLET: 'The last step is to create your first splitbits wallet. Later you can import or recover other wallets that you have.',
      WELCOME: 'Swipe to learn more.',
    },
  },

  ES: {
    ACCEPT: 'Aceptar',
    ADD_NOTE: 'Añadir nota',
    ADDRESS: 'Direccion',
    ARCHIVE_WALLET: 'Archiva esta cartera',

    BALANCE: 'Balance',

    CANCEL_REQUEST: 'Cancelar peticion',
    CHANGE_YOUR_AVATAR: 'Cambia tu avatar',
    CHOOSE_A_FRIEND: 'Selecciona un amigo',
    CHOOSE_CURRENCY: 'Selecciona tu moneda local',
    CHOOSE_EXISTING_PHOTO: 'Elige una foto existente',
    CHOOSE_LANGUAGE: 'Elige tu idioma',
    CONCEPT: 'Concepto',
    CONFIRMATIONS: 'Confirmaciones',
    COPYRIGHT: 'Creado por una banda de superheroes desde Londres. Gracias por tu apoyo!',
    CREATE: 'Crear',
    CREATE_BACKUP: 'Crea una copia de seguridad',
    CREATE_FIRST_WALLET: 'Crea tu primera cartera',

    DATE: 'Fecha',
    DEPOSIT: 'Deposito',

    ERROR_CONNECTION: 'Oops, parece que no estas conectado al servidor Splitbits.',

    FEE: 'Comision',
    FRIENDS: 'Amigos',
    FROM: 'De',

    HASH: 'Hash',
    HINT_FIND_BY_NAME: 'Otras personas solo te encontraran si has definido un nombre.',

    IMPORT: 'Importar',
    IMPORT_ADDRESS: 'Si importas una direccion publica tu cartera sera de solo lectura',

    LANGUAGE: 'Idioma',
    LOCAL_CURRENCY: 'Moneda local',

    NAME: 'Nombre',
    NEW_WALLET: 'Nueva cartera',
    NEXT: 'Siguiente',

    PAPER_KEY: 'Llave de Papel',
    PAPER_KEY_DONE: 'Ya he escrito mi llave de papel',
    PAPER_WALLET: 'Su llave de papel es la única forma de restaurar tu cartera, si lo pierde, se la roban, se rompe o se actualiza su teléfono. Esta es su lista de palabras para anotar en un pedazo de papel y mantenerlo a salvo.',
    PAY: 'Pagar',
    PAYMENT: 'Pago',
    PAYMENT_REQUEST: 'Solicitud de Pago',
    PORTFOLIO: 'Mantente al tanto de tu cartera. En cualquier momento. En cualquier lugar.',
    PROCESSING: 'Procesando...',
    PROFILE_QR: 'Este QR ayudará a tus amigos a encontrarte fácilmente.',

    READ_ONLY: 'Solo lectura',
    RECOVER_PAPER_WALLET: 'Recuperar otra cartera le permite acceder y administrar una billetera diferente en este dispositivo. Ingrese la clave de papel.',
    RECOVER: 'Recuperar',
    REQUEST: 'Solicitar',
    REQUEST_MONEY: 'Pedir dinero',
    REQUEST_MONEY_HINT: 'Puedes pedir dinero en tu red privada.',
    REQUEST_MONEY_HINT_NO_FRIENDS: 'Debes añadir amigos para poder pedir dinero.',

    SEARCH: 'Buscar...',
    SEND: 'Enviar',
    SEND_MONEY: 'Enviar dinero',
    SEND_MONEY_HINT: 'Envía dinero a cualquier cartera en el mundo.',
    SEND_MONEY_HINT_NO_BALANCE: 'Recargue su cartera para enviar dinero.',
    SEND_MONEY_HINT_READ_ONLY: 'No puedes enviar dinero desde una cartera en solo lectura.',
    SETTINGS: 'Opciones',
    SET_PIN_CODE: 'Establece tu codigo PIN',
    SKIP: 'Saltar',
    START: 'Comenzar',
    STATE: 'Estado',
    SWITCH_PRO: 'Pasate a PRO',

    TAKE_PHOTO: 'Toma una foto',
    TO: 'Para',
    TRANSACTION: 'Transaccion',
    TYPE_OF_TRANSACTION: 'Tipo de transaccion',
    TYPE_OF_WALLET: 'Tipo de cartera',

    USE_PUBLIC_ADDRESS: 'o una direccion publica',
    USE_FINGERPRINT: 'Usa tu huella para desbloquear',

    WAIT_A_MOMENT: 'Espera un momento',
    WALLET: 'Cartera',
    WORD: 'Palabra',

    CAPTION: {
      ARCHIVE_WALLET: 'Si no quieres utilizar esta cartera por un tiempo.',
      CAMERA_PERMISSION: 'Necesitas acceder a la camera para poder leer codigos QR.',
      CREATE_BACKUP: 'La manera mas sencilla para controlar tu cartera.',
      EXCHANGE: 'Usa tu moneda local',
      NETWORK: 'Tu red privada',
      PRIVACY: 'Tu privacidad es importante',
      PRIVATE_KEYS: 'Dueño de tus llaves',
      QR_CODE: 'Coloca el codigo QR dentro del area.',
      SWITCH_PRO: 'Super poderes para tu cartera.',
      WALLET: 'Enhorabuena, ya estas listo!',
      WELCOME: 'Bienvenido a Splitbits',
    },
    HINT: {
      EXCHANGE: 'Este mundo todavía se paga con monedas locales. No te preocupes, te hacemos la vida más fácil a la hora de pagar con tus cripto-monedas.',
      NETWORK: 'Olvidate de direcciones públicas o códigos QR. Puedes crear tu propia red privada de amigos para acelerar todas tus pagos.',
      PRIVACY: 'No necesitamos tus datos personales. No queremos saber tu email o tus redes sociales. Solo queremos que disfrutes de Splitbits.',
      PRIVATE_KEYS: 'Tus claves privadas siempre van contigo, nunca las guardamos en nuestra nube. Te ofrecemos herramientas para que pueda recuperarlas fácilmente.',
      WALLET: 'El último paso es crear tu primera cartera Splitbits. Mas tarde podras importar o recuperar otras carteras que tengas.',
      WELCOME: 'Desliza para obtener más información.',
    },
  },
};
